liip_imagine:
   # valid drivers options include "gd" or "gmagick" or "imagick"
  #  driver: "gd"

   # define your filter sets under this option
   filter_sets:

       # an example thumbnail transformation definition
       # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
       squared_thumbnail:
           # set your image quality defaults
           jpeg_quality:          85
           png_compression_level: 8

           filters:
               relative_resize:

                    # given 50x40px, output 75x60px using "heighten" option
                   heighten: 32
               # scale and square the image to the given dimensions
            #    thumbnail:
            #        size:          [32, 32]
            #        mode:          outbound
            #        allow_upscale: true
            #    # create border by placing image on larger black background
            #    background:
            #        size:     [35, 35]
            #        position: center
            #        color:    '#fff'

       720_thumbnail:
           # set your image quality defaults
           jpeg_quality:          85
           png_compression_level: 8
           filters:
               auto_rotate: ~
               strip: ~
               thumbnail:
                   size:          [720, 720]
                   mode:          outbound
                   allow_upscale: true
               background:
                   size:     [723, 723]
                   position: center
                   color:    '#fff'
